### ISSUE TITLE
Generates non-manifold output, LUT might be off

### ISSUE THREAD

**Issue by exavi** [dominikwodniok/dualmc#1]
Hi, this is a brilliant Dual MC implementation, thanks for sharing it!

According to the original paper, Dual Marching Cubes should have two-manifold output, but running the caffeine example non-manifold output is generated. (T junctions can be found around the side molecules)

I suspect that the table could have some value(s) off, how was it generated? I'd like to have a go at adjusting the table values to make it generate clean meshes ;)

**Comment by dominikwodniok** [comment]
Hi, you are right about the non-manifold output. This shouldn't happen. But I couldn't find the T junctions you talked about. 
Unfortunately, I handcrafted the table a long time ago. I definitely should write some code for generating the table. This would also allow to generate different tables for the ambiguous cases. 
If you don't mind I will fix this issue myself, but I won't stop you if you want to have a go.

**Comment by exavi** [comment]
Thanks for getting back to me, after re-reading the paper, I'm not so sure if what I'm seeing is the case Nielson talks about in section 5.3 (Additional Remark) it says that if configurations C16 or C19 in their tables share a common face, two edges will be coincident in the output, which I believe is what ends up creating this non-manifold edge config, which is funny, because it contradicts everything it says at the beginning of the paper regarding two-manifold outputs... :)

If you run the caffeine example and have a 3d editor/viewer that can display vertex numbers, the edge I am talking about can be seen between in the images attached.

<img width="681" alt="non-manifold1" src="https://user-images.githubusercontent.com/2195314/34408696-bb309eda-ebc5-11e7-92c5-ab707c8c08f5.png">
<img width="717" alt="non-manifold2" src="https://user-images.githubusercontent.com/2195314/34408697-bb58bcbc-ebc5-11e7-8691-f0d48823b6d1.png">

If you don't have an editor that can display these, a two manifold mesh can always be checked for "manifoldness" by checking that an ordered pair of vertex indices isn't found more than once in the mesh (as adjacent triangles will always have inverted order, ie for an edge between indices 55 and 56, there can only be two entries, (55,56) and (56,55) but each one of these can only be found once) This can be checked directly from reading the output OBJ and storing "ordered pairs/edges" in a set, if the entry is already in the set, the edge will be non-manifold.

What do you think? Do you think that this scenario is the one listed in the paper?

Cheers!

**Comment by dominikwodniok** [comment]
Thank you very much for your hint regarding section 5.3. I was able to experimentally verify that the edge is indeed created by two neighboring C16 configurations. I also wrote some code for automatically generating the table and was able to verify the correctness of the handcrafted table.

So yeah... Depending on the definition of non-manifold meshs it seems like dual marching cubes can produce non-manifold edges. I know there are people who still would call this a 2-manifold mesh (e.g. the paper author). For me it would be desirable to change C16 and C19 in a way that gets rid of this edge.

Digging into the code I also noticed that generated meshes are inside-out. I should fix this...

Again thanks for your comments....

**Comment by dominikwodniok** [comment]
A simple solution for the non-manifold problem is provided in chapter 3.3.5 of the book "Isosurfaces: Geometry, Topology, and Algorithms" from Rephael Wenger. He calls his approach Manifold Dual Marching Cubes. If no one else wants to implement it I will do it as soon as I find the time.
I will close this issue as the non-manifold edge is part of the original Dual Marching Cubes algorithm.
