### ISSUE TITLE
Missing gentables.h

### ISSUE THREAD

**Issue by kwuerl** [dominikwodniok/dualmc#2]
It seems that the gentables.h file is missing in the repository.
Can you maybe check this?

**Comment by dominikwodniok** [comment]
You are right. I forgot to add it and a missing main.cpp file because they somehow got filtered out by the gitignore file. Even worse, I had to rewrite them because I could not find them anymore. Now they are in the repository.

**Comment by dominikwodniok** [comment]
Seems like no further action is required here.
