### ISSUE TITLE
Problem with dimX != dimY != dimZ != 2^n

### ISSUE THREAD

**Issue by kwuerl** [dominikwodniok/dualmc#3]
For my 261x131x137 volume the result exhibits strange distortions:
Every second z-voxel-layer is empty and the y-voxels seem to be duplicated.
If i scale the grid up to 261x261x261 it works flawlessly.
Do you have any idea what may cause this?

**Comment by dominikwodniok** [comment]
I wasn't able to reproduce this issue. Did you perhaps specify the volume dimensions in the wrong order? Or could you perhaps provide more information?

**Comment by dominikwodniok** [comment]
I will close this for now due to no additional feedback.
