### ISSUE TITLE
Can output mesh be updated in parallel Chunks?

### ISSUE THREAD

**Issue by Peach1** [dominikwodniok/dualmc#4]
This is a really great Manifold Dual Marching Cubes implementation!

How would you extend `buildSharedVerticesQuads` to update only a subsection of its quad&vertex output instead of exporting everything at once? 

I want to use dualmc to make an editable Voxel terrain system that *updates small parts of a large terrain in realtime*.

For example, a data set of 512^3 would be divided into 8x8x8 chunks, and editing the iso of a voxel at location (0,0,0) only updates the mesh output for (0,0,0) to (7,7,7).

Some pseudocode for chunk processing:

```cpp

int32_t chunkx = 0;
int32_t chunky = 0;
int32_t chunkz = 0;

int32_t chunksize = 8;

....

void DualMC<T>::buildSharedVerticesQuads(
        VolumeDataType const iso,
        std::vector<Vertex> & vertices,
        std::vector<Quad> & quads
        )

....

for(int32_t cz = 0; cz < reducedZ; ++cz) // iterate voxels
		{
			for(int32_t cy = 0; cy < reducedY; ++cy)
			{
				for(int32_t cx = 0; cx < reducedX; ++cx)
				{
					int32_t x = cx+chunkx; // offset chunk size
					int32_t y = cy+chunky;
					int32_t z = cz+chunkz;
					
					x = CLAMP(x,chunkx,chunkx+chunksize);
					y = CLAMP(y,chunky,chunky+chunksize);
					z = CLAMP(z,chunkz,chunkz+chunksize);
					
					x = CLAMP(x,0,reducedX-1);
					y = CLAMP(y,0,reducedY-1);
					z = CLAMP(z,0,reducedZ-1);
					
					// is this parallelizable?
					// can each voxel be processed separately?
					CalcDualPoint(x,y,z,
								  iso,
								  vertices, quads);
				}
			}
		}
```

How would you allocate the vertices&quads output vectors once, to the max mesh size needed for a given resolution, then later reuse those same vectors, quickly updating only a small chunk of the mesh output at a time?

Any help would be appreciated, thank you again for the awesome library!

**Comment by dominikwodniok** [comment]
Hi,
If you already partitioned your volume data into chunks you can do this right away. You can simply call `reserve()` on the vertices and quad vectors before calling `build()`. Build  only calls `clear()` on the vectors before filling them. According to the specification `clear()` only sets the vector size to zero but keeps the reserved memory.
The maximum number of dual points per voxel cell made from 8 voxel corners is 4.
The maximum number of quads per chunk is the number of voxel cell edges of the chunk.
This also improves locality of volume data access.

If the volume data is not partitioned into chunks I have to add an additional build method for this.

Separate chunks can be processed in parallel when they have separate vertex and quad vectors. But every thread currently also needs its own DualMCBuilder instance. I think there is not enough work for parallelizing the computations inside of a chunk.

Hope this helps.
