### ISSUE TITLE
Seamless tiles

### ISSUE THREAD

**Issue by malytomas** [dominikwodniok/dualmc#5]
Hi, I really like this marching cubes. Especially that it outputs quads rather than triangles.
But I am having trouble with using this library to generate tiled output. I always get holes in between tiles (or overlapping triangles on seams). Could you please help me? I have prepared a simplified example app.
https://github.com/malytomas/dualmc-tiles-test/tree/master
![dualmc-tiles](https://user-images.githubusercontent.com/18198295/49864034-d9f5ff00-fe01-11e8-9f40-c6cacdde5269.png)

**Comment by dominikwodniok** [comment]
Hi. Sorry for getting back to you so late. And thanks for the example app. It helped to find the solution.
Dual marching cubes creates vertices inside the cubes, which have the voxel data at their corners. For the output of the tiles to be connected, the tiles must share a border of one cube thickness. That means they must share a two voxel thick border. I hope this is not a downer for you.
You can achieve this in your example code by setting:
```
int dim = 50;
int dim1 = dim - 3;
int dim2 = dim - 3;
```
And here a picture of my output:
![tileddualmc](https://user-images.githubusercontent.com/6384465/50932078-d4bdbb80-1464-11e9-873b-13b01d0ccfb8.png)

Cheers

**Comment by malytomas** [comment]
Thanks for the reply. I will add some form of clipping to avoid z-fighting on the borders and it will hopefully work well :D
