### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by trsh** [dominikwodniok/dualmc#7]
Your screenshot looks like surface nets?!

**Comment by dominikwodniok** [comment]
Hi.
I'm sorry but I'm not sure if this is a remark or a question, As stated in the readme this is an implementation of the Dual Marching Cubes algorithm from Gregory M. Nielson. Oddly enough, I've never heard of surface nets before. From a quick search into surface nets I saw that they are at least similar (or even identical) to the dual marching cubes algorithm.

**Comment by trsh** [comment]
Yes, sorry
